### ISSUE TITLE
mvn build error

### ISSUE THREAD

**Issue by patricerosay** [vincent-zurczak/felix-target-platform-with-tycho#1]
Hi,
I've downloaded your example. When I build it (mvn install) , I have the error bellow.
any idea ?
cheers.
## [WARNING] No explicit target runtime environment configuration. Build is platform dependent.

constituent[0]: file:/C:/dev/apache-maven-3.3.1/lib/aether-api-1.0.2.v20150114.jar
constituent[1]: file:/C:/dev/apache-maven-3.3.1/lib/aether-connector-basic-1.0.2.v20150114.jar
constituent[2]: file:/C:/dev/apache-maven-3.3.1/lib/aether-impl-1.0.2.v20150114.jar
constituent[3]: file:/C:/dev/apache-maven-3.3.1/lib/aether-spi-1.0.2.v20150114.jar
constituent[4]: file:/C:/dev/apache-maven-3.3.1/lib/aether-transport-wagon-1.0.2.v20150114.jar
constituent[5]: file:/C:/dev/apache-maven-3.3.1/lib/aether-util-1.0.2.v20150114.jar
constituent[6]: file:/C:/dev/apache-maven-3.3.1/lib/aopalliance-1.0.jar
constituent[7]: file:/C:/dev/apache-maven-3.3.1/lib/cdi-api-1.0.jar
constituent[8]: file:/C:/dev/apache-maven-3.3.1/lib/commons-cli-1.2.jar
constituent[9]: file:/C:/dev/apache-maven-3.3.1/lib/commons-io-2.2.jar
constituent[10]: file:/C:/dev/apache-maven-3.3.1/lib/commons-lang-2.6.jar
constituent[11]: file:/C:/dev/apache-maven-3.3.1/lib/guava-18.0.jar
constituent[12]: file:/C:/dev/apache-maven-3.3.1/lib/javax.inject-1.jar
constituent[13]: file:/C:/dev/apache-maven-3.3.1/lib/jsoup-1.7.2.jar
constituent[14]: file:/C:/dev/apache-maven-3.3.1/lib/jsr250-api-1.0.jar
constituent[15]: file:/C:/dev/apache-maven-3.3.1/lib/maven-aether-provider-3.3.1.jar
constituent[16]: file:/C:/dev/apache-maven-3.3.1/lib/maven-artifact-3.3.1.jar
constituent[17]: file:/C:/dev/apache-maven-3.3.1/lib/maven-builder-support-3.3.1.jar
constituent[18]: file:/C:/dev/apache-maven-3.3.1/lib/maven-compat-3.3.1.jar
constituent[19]: file:/C:/dev/apache-maven-3.3.1/lib/maven-core-3.3.1.jar
constituent[20]: file:/C:/dev/apache-maven-3.3.1/lib/maven-embedder-3.3.1.jar
constituent[21]: file:/C:/dev/apache-maven-3.3.1/lib/maven-model-3.3.1.jar
constituent[22]: file:/C:/dev/apache-maven-3.3.1/lib/maven-model-builder-3.3.1.jar
constituent[23]: file:/C:/dev/apache-maven-3.3.1/lib/maven-plugin-api-3.3.1.jar
constituent[24]: file:/C:/dev/apache-maven-3.3.1/lib/maven-repository-metadata-3.3.1.jar
constituent[25]: file:/C:/dev/apache-maven-3.3.1/lib/maven-settings-3.3.1.jar
constituent[26]: file:/C:/dev/apache-maven-3.3.1/lib/maven-settings-builder-3.3.1.jar
constituent[27]: file:/C:/dev/apache-maven-3.3.1/lib/org.eclipse.sisu.inject-0.3.0.jar
constituent[28]: file:/C:/dev/apache-maven-3.3.1/lib/org.eclipse.sisu.plexus-0.3.0.jar
constituent[29]: file:/C:/dev/apache-maven-3.3.1/lib/plexus-cipher-1.7.jar
constituent[30]: file:/C:/dev/apache-maven-3.3.1/lib/plexus-component-annotations-1.5.5.jar
constituent[31]: file:/C:/dev/apache-maven-3.3.1/lib/plexus-interpolation-1.21.jar
constituent[32]: file:/C:/dev/apache-maven-3.3.1/lib/plexus-sec-dispatcher-1.3.jar
constituent[33]: file:/C:/dev/apache-maven-3.3.1/lib/plexus-utils-3.0.20.jar
constituent[34]: file:/C:/dev/apache-maven-3.3.1/lib/sisu-guice-3.2.5-no_aop.jar
constituent[35]: file:/C:/dev/apache-maven-3.3.1/lib/slf4j-api-1.7.5.jar
constituent[36]: file:/C:/dev/apache-maven-3.3.1/lib/slf4j-simple-1.7.5.jar
constituent[37]: file:/C:/dev/apache-maven-3.3.1/lib/wagon-file-2.8.jar
constituent[38]: file:/C:/dev/apache-maven-3.3.1/lib/wagon-http-2.8-shaded.jar
constituent[39]: file:/C:/dev/apache-maven-3.3.1/lib/wagon-http-shared-2.8.jar
constituent[40]: file:/C:/dev/apache-maven-3.3.1/lib/wagon-provider-api-2.8.jar
## constituent[41]: file:/C:/dev/apache-maven-3.3.1/conf/logging/

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
        at org.eclipse.tycho.core.maven.utils.PluginRealmHelper.execute(PluginRealmHelper.java:86)
        at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.getDependencyMetadata(P2TargetPlatformResolver.java:146)
        at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.setupProjects(P2TargetPlatformResolver.java:128)
        at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.setupProject(DefaultTychoDependencyResolver.java:81)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:77)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by vincent-zurczak** [comment]
Hi,

I think this is related to your Maven version. At the time I posted this sample, I was using a prior version of Maven (3.0.x I think). Since Maven 3.1 (and higher), the Aether library has changed its hosting. It used to be hosted at Sonatype and is now an Eclipse project.

Roughly, your stack indicates it did not find `org.sonatype.aether.RepositorySystemSession`, which is normal with Maven 3.1. The class should now be called something like `org.eclipse.aether.RepositorySystemSession`. Just for your information, I mentioned this Aether change in [one of my last blog articles](https://vzurczak.wordpress.com/2016/01/08/finding-dependencies-artifacts-in-your-maven-plug-in/). I do not expect you had read it, but I think it explains your error.

You can either try with an older version of Maven, or better, try with a more recent of Tycho, one that is compliant with Maven >= 3.1.

**Comment by patricerosay** [comment]
corrected by changing the tycho version number.
tx
